# Generated by Django 3.2.9 on 2021-12-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.CharField(max_length=400)),
                ('composition', models.TextField()),
                ('description', models.TextField()),
                ('uses', models.TextField()),
                ('benefits', models.TextField()),
                ('sideEffects', models.TextField()),
                ('safetyAdvice', models.TextField()),
                ('hwToUse', models.TextField()),
                ('works', models.TextField()),
                ('faq', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(blank=True, upload_to='images')),
                ('img3', models.ImageField(blank=True, upload_to='images')),
                ('img4', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
