# Generated by Django 3.2.9 on 2022-01-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultationcategory',
            fields=[
                ('category', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('categoryimage', models.ImageField(upload_to='images')),
                ('categorydescription', models.CharField(max_length=30)),
                ('categorydiseases', models.CharField(max_length=30)),
                ('faqquestion1', models.TextField()),
                ('faqanswer1', models.TextField()),
                ('faqquestion2', models.TextField(blank=True)),
                ('faqanswer2', models.TextField(blank=True)),
                ('faqquestion3', models.TextField(blank=True)),
                ('faqanswer3', models.TextField(blank=True)),
                ('faqquestion4', models.TextField(blank=True)),
                ('faqanswer4', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorconsultation',
            fields=[
                ('doctorimage', models.ImageField(upload_to='images')),
                ('doctorid', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('doctorname', models.CharField(max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('educationdetails', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='consultationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctorconsultation')),
            ],
        ),
    ]
