# Generated by Django 3.2.9 on 2022-01-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultationcategory_consultationform_doctorconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcategory',
            name='categorydescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='categorydiseases',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='doctorid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
