# Generated by Django 3.2.9 on 2022-01-17 17:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
    ]
