# Generated by Django 3.2.9 on 2022-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220102_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='faq',
        ),
        migrations.AddField(
            model_name='product',
            name='faqanswer1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqanswer2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqanswer3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqanswer4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqanswer5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqquestion1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqquestion2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqquestion3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqquestion4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faqquestion5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='organcategory',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
