# Generated by Django 3.2.9 on 2022-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_repository_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='id',
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
