# Generated by Django 3.2.9 on 2022-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220110_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
