import Blognews from "./Blognews";
const cards=[["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue. ","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/35959bdd15b6322d8cae5a14afee9a80.png?dim=100x0&dpr=1.25&q=100","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet posuere felis, nec sollicitudin nulla. Mauris luctus lacus a turpis bibendum viverra. Duis sed eros augue.","Cras blandit interdum diam at interdum. Sed at odio ante. Fusce nec lacinia elit. Proin arcu diam, scelerisque nec eros eu, lobortis rhoncus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis euismod arcu, sit amet ultricies felis laoreet sed. Maecenas at quam sed ipsum"],
     ["https://cdn01.pharmeasy.in/dam/discovery/categoryImages/7a74f126363e3deeac80a246471767f9.png?dim=100x0&dpr=1.25&q=100","Morbi eros ex, consectetur quis dolor quis, tempus posuere nunc. Aliquam hendrerit mi a finibus luctus. Ut eget lacinia ex. Vivamus in ex nec orci viverra suscipit.","Nullam sit amet nisi cursus, tempus diam a, varius lectus. Nunc porta leo nec sollicitudin fringilla. In vehicula diam in turpis varius, sed fringilla leo aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum luctus ut velit non vestibulum. Fusce tristique pulvinar lectus, ut convallis diam malesuada quis"]
]
function BlogPage(props){
    return(
        cards.map((card)=>{
            return <Blognews img={card[0]} headlines={card[1]} description={card[2]}/>
        })
    );
    }
    export default BlogPage;